services:
  db:
    image: postgres:15
    container_name: beauty-salon-scheduler-postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=beauty-salon-scheduler
    ports:
      - "5432:5432"