CREATE TABLE IF NOT EXISTS authorities (
    authority        VARCHAR(255) NOT NULL,
    PRIMARY KEY (authority)
);

CREATE TABLE IF NOT EXISTS users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    about            VARCHAR(255),
    email            VARCHAR(255) NOT NULL,
    face_shape       VARCHAR(255) CHECK (face_shape IN ('ROUND', 'SQUARE', 'TRIANGLE', 'OVAL', 'DIAMOND')),
    hair_curl        VARCHAR(255) CHECK (hair_curl  IN ('STRAIGHT', 'WAVY', 'CURLY', 'KINKY')),
    instagram        VARCHAR(255),
    name             VARCHAR(255) NOT NULL,
    password         VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_authority_junction (
    user_id          BIGINT NOT NULL,
    authority        VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, authority)
);

CREATE TABLE IF NOT EXISTS beauty_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description      VARCHAR(255) NOT NULL,
    duration         INTEGER NOT NULL,
    name             VARCHAR(255) NOT NULL,
    price            FLOAT(53) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS appointments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    active           BOOLEAN NOT NULL,
    end_interval     TIMESTAMP(6),
    observations     VARCHAR(255),
    start_interval   TIMESTAMP(6) NOT NULL,
    total_price      FLOAT(53),
    customer_id      BIGINT NOT NULL,
    employee_id      BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS appointment_beauty_item_junction (
    appointment_id   BIGINT NOT NULL,
    beauty_item_id   BIGINT NOT NULL
);

ALTER TABLE IF EXISTS users ADD CONSTRAINT UK_users_email UNIQUE (email);

ALTER TABLE IF EXISTS user_authority_junction ADD CONSTRAINT FK_user_authority_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE IF EXISTS user_authority_junction ADD CONSTRAINT FK_user_authority_authority FOREIGN KEY (authority) REFERENCES authorities (authority);

ALTER TABLE IF EXISTS appointments ADD CONSTRAINT FK_appointments_customer FOREIGN KEY (customer_id) REFERENCES users (id);
ALTER TABLE IF EXISTS appointments ADD CONSTRAINT FK_appointments_employee FOREIGN KEY (employee_id) REFERENCES users (id);

ALTER TABLE IF EXISTS appointment_beauty_item_junction ADD CONSTRAINT FK_appointment_beauty_item_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id);
ALTER TABLE IF EXISTS appointment_beauty_item_junction ADD CONSTRAINT FK_appointment_beauty_item_beauty_item FOREIGN KEY (beauty_item_id) REFERENCES beauty_items (id);
